name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Go tests
        run: go test --cover ./...

      - name: setup gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run security checks
        run: gosec ./...
  formatting:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Go fmt
        run: test -z $(go fmt ./...)

      - name: Run staticcheck
        run: staticcheck ./...
